### ISSUE TITLE
Das3 cdf write for merged datasets

### ISSUE THREAD

**Issue by senortonito** [das-developers/das2C#8]
Command:
das3_cdf -i "https://tracers-dev.physics.uiowa.edu/stream/source/preflight/ql/magic/fm-2/merged/flex?read.time.min=2024-02-20T20:56&read.time.max=2024-02-20T21:07" -o ~/

Error:
ERROR: Error parsing units string '%' at byte number 1  (reported from das2/units.c:646, _Units_strToComponents)

**Comment by cpiker** [comment]
It looks like das3_cdf is working as designed in this instance.  There's an error in the upstream source, so we'll fix it there.

**Comment by cpiker** [comment]
Unit parsing in units.c is working as designed, but it's design does not allow "%" as a unit name, however "percent" would be.  This is inconsistent and will be fixed.

Thanks for submitting the issue.
